// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aieomcawcimnvwyizsyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpZW9tY2F3Y2ltbnZ3eWl6c3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNjY2OTYsImV4cCI6MjA1NTY0MjY5Nn0.Rt6OUKRo_gowbVlOcsC-97molkNYMYbMa2E7pV60_Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);